### ISSUE TITLE
../checkpoint/550000.pt

### ISSUE THREAD

**Issue by auguser** [memesoo99/regan#1]
hi，i can't find ../checkpoint/550000.pt,please tell me where i can find,thanks~~

**Comment by memesoo99** [comment]
Sorry for the long wait. I'm not sure if you need this anymore but I will post it anyway.

[Pretrained Weights](https://drive.google.com/drive/folders/1uwazXGD_gxADuFRCRhB2McnT1kUFYf4v?usp=sharing)

./checkpoint/550000.ptt, is now named as ./checkpoint/FewShotSeg_human.pt
